### ISSUE TITLE
some shapes can not visualized

### ISSUE THREAD

**Issue by swordcrash** [algenty/grafana-flowcharting#105]
Hi,

I try to use the shapes in "cisco 19", but it failed to show the right picture.
Does the v.0.6.0 support those shapes?

Thanks!

**Comment by algenty** [comment]
Hi @swordcrash 
Need to try, can you test again with version 0.7.0 in download setion
enty.github.io/flowcharting-repository/

**Comment by swordcrash** [comment]
Hi @algenty 


I use the 0.7.0_new branch but failed to run yarn build. 
```
yarn run v1.21.1
$ grafana-toolkit plugin:build
module.js:478
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/grafana/plugins/grafana-flowcharting/node_modules/tslint/lib/utils.js:21:10)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I'm a newbie on node, didn't know how to solve it. 
I have to use other shapes, still thanks for a great job on this project.

**Comment by swordcrash** [comment]
I notice the Cisco19 has not the property of "Edit Shape" on draw.io online. Is that mean I can't add the <shape></shape> in src/libs/drawio/stencils?

**Comment by Alcarin** [comment]
Any update?

**Comment by algenty** [comment]
Can you try 0.7.0 snapshot in https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by algenty** [comment]
Without answer i close ticket
