### ISSUE TITLE
Grafana 8 Compatibility

### ISSUE THREAD

**Issue by d02023287** [algenty/grafana-flowcharting#302]
When adding this as a visualization in grafana 8 panel saving gets an error

An unexpected error happened
DetailsTypeError: Cannot read property 'startsWith' of undefined

    at C (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:1196:1771)
    at k (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:1198:392)
    at rt
    at at (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:3076:1106)
    at h (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:5435:19792)
    at Di (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:3726:564)
    at Ei (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:3726:848)
    at l (https://sbx.qnetdashboard.cms.gov/public/build/vendors~app.90f320b382a70cd0232d.js:2:68275)
    at Nr (https://sbx.qnetdashboard.cms.gov/public/build/app.90f320b382a70cd0232d.js:5625:300)

**Comment by merwync** [comment]
Same issue with v8.0.3

**Comment by merwync** [comment]
Issues resolved on my end, network misconfiguration

**Comment by Rumbelstilzchen** [comment]
@merwync How did you solve the issue? It seems that I have a similar problem since grafana 8. At my installation none of the 3rd party plugins are working...

**Comment by ronansalmon** [comment]
looks like it is working fine with grafana 8.1.2.

**Comment by moseskt** [comment]
@ronansalmon do you mind sharing pointers? I am struggling to get it working in Grafana 8.1.2 using the getting started guide. Just cannot find where the metrics and mapping tabs in the screenshots are. Any help appreciated
